name: Go Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # Your go.mod file specifies go 1.24.6, this should be compatible.

    - name: Run unit tests
      # The -v flag provides verbose output. The ./... pattern runs tests in all subdirectories.
      run: go test -v ./...